### ISSUE TITLE
improve readme/docs

### ISSUE THREAD

**Issue by FlorianLudwig** [tutorcruncher/morpheus#130]
The readme leaves out some 

# activate.sh
What does `source activate.sh` refer to? Unclear from readme. The repository itself does not contain a `activate.sh`.

# how to sent an email
The readme does not specify how to actually sent emails using morpheus.

# persistence
what is postgres used for? what is redis used for?  Does it persist a message I tried to send via http api call but couldn't send? Does it retry?

**Comment by samuelcolvin** [comment]
`activate.sh` is used to store secrets like API keys, I'll look later and give the structure of our one.

emails are currently sent using mandrill, but in future we intend to migrate to aws ses.

redis is used for queuing (via [arq](https://github.com/samuelcolvin/arq)) and some caching, postgres is used to store
* all emails and sms sent
* redirect keys and click for click tracking
* opens and delivery failure etc.

Happy to provide an example `activate.sh`, but you should be aware this is primarily an internal project to TutorCruncher, we're not going to document it massively or make big changes unless we need them. "your milage may vary"

**Comment by samuelcolvin** [comment]
Here's the skeleton of our `activate.sh` script:

```bash
#!/usr/bin/env bash
. ~/.bashrc
. env/bin/activate
export APP_DEPLOY_NAME='morpheus-pg'
export SYSLOG_HOSTNAME='morpheus-pg'

export LOGSPOUT_ENDPOINT='syslog://...'
export RAVEN_DSN='.'

export APP_AUTH_KEY='...'
export APP_USER_AUTH_KEY='...'

export APP_MANDRILL_KEY='...'

export APP_PG_DSN='postgres://...'

export APP_HOST_NAME='morpheus.tutorcruncher.com'
export APP_PUBLIC_LOCAL_API_URL='https://morpheus.tutorcruncher.com'
export APP_ADMIN_BASIC_AUTH_PASSWORD='...'
export APP_CLICK_HOST_NAME='l.tutorcruncher.com'

export APP_MESSAGEBIRD_KEY='...'
export APP_MESSAGEBIRD_PRICING_USERNAME='...'
export APP_MESSAGEBIRD_PRICING_PASSWORD='...'

export APP_STATS_TOKEN='...'

export INFLUXDB_URL='https://...'
export INFLUXDB_PASSWORD='...'

echo "enabling docker machine..."
eval $(docker-machine env morpheus4)

export MODE='PRODUCTION'
export PS1="PROD $PS1"
```
